Repository DeveloperAcademy-POSTECH/MC3_TEAM1_LATER, pull requests merged in 2022-07, with the labels that each got.

#4 [Feat] Main.storyboard 내 TaBarController 기본 세팅
  RoomEscape/RoomEscape/Base.lproj/Main.storyboard
Labels: enhancement

#21 RoomCell ReusableCell 추가
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomCell.swift
  RoomEscape/RoomEscape/Views/RoomCell.xib
Labels: enhancement

#23 [Feat] Feat/pick view to Develop
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomCell.swift
  RoomEscape/RoomEscape/Views/RoomCell.xib
Labels: documentation

#22 ThemeCompare 스토리보드 추가
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/ViewControllers/ThemeCompareViewController.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomCell.swift
  RoomEscape/RoomEscape/Views/RoomCell.xib
  RoomEscape/RoomEscape/Views/ThemeCompare.storyboard
Labels: enhancement

#27 [Feat] Home.storyboard / HomeViewController 구현
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Models/StoreModel.swift
  RoomEscape/RoomEscape/ViewControllers/HomeViewController.swift
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/Views/Home.storyboard
  RoomEscape/RoomEscape/Views/HomeCollectionViewCell.swift
  RoomEscape/RoomEscape/Views/HomeTableViewCell.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.swift
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.xib
  RoomEscape/RoomEscape/Views/RoomTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomTableViewCell.xib
Labels: enhancement

#26 Feat/detail view
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/ViewControllers/DetailViewController.swift
  RoomEscape/RoomEscape/Views/Detail.storyboard
Labels: enhancement

#28 Feat/home view
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Models/StoreModel.swift
  RoomEscape/RoomEscape/ViewControllers/HomeViewController.swift
  RoomEscape/RoomEscape/Views/Home.storyboard
  RoomEscape/RoomEscape/Views/HomeCollectionViewCell.swift
  RoomEscape/RoomEscape/Views/HomeTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.swift
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.xib
  RoomEscape/RoomEscape/Views/RoomTableViewCell.xib
Labels: enhancement, Ready to be closed

#29 Style/Asset Color 추가
  RoomEscape/RoomEscape/Assets.xcassets/Color/star.colorset/Contents.json
  RoomEscape/RoomEscape/Extensions/Extension.swift
Labels: enhancement

#30 PickView, MakeTeamView UI 구현 및 입력 로직 추가
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Extensions/Extension.swift
  RoomEscape/RoomEscape/ViewControllers/MakeTeamViewController.swift
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/ViewControllers/TeamCell.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
Labels: enhancement

#31 [Feat] ThemeCompareViewController 작업 진행 중
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Extensions/UILabel+Extension.swift
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/ViewControllers/ThemeCompareViewController.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomTableViewCell.xib
  RoomEscape/RoomEscape/Views/ThemeCompare.storyboard
Labels: enhancement

#40 Feat/detail view
  RoomEscape/RoomEscape/Models/StoreModel.swift
  RoomEscape/RoomEscape/ViewControllers/DetailViewController.swift
  RoomEscape/RoomEscape/Views/Detail.storyboard
Labels: enhancement

#42 Feat/detail view
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Assets.xcassets/AppIcon.appiconset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/Background.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/Background2.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/Main.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/star.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/text1.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/text2.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/text3.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/text4.colorset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Color/text5.colorset/Contents.json
  RoomEscape/RoomEscape/Base.lproj/Main.storyboard
  RoomEscape/RoomEscape/Extensions/Constants.swift
  RoomEscape/RoomEscape/Extensions/Extension.swift
  RoomEscape/RoomEscape/Extensions/UILabel+Extension.swift
  RoomEscape/RoomEscape/Managers/JSONDataManager.swift
  RoomEscape/RoomEscape/Models/StoreModel.swift
  RoomEscape/RoomEscape/PohangData.json
  RoomEscape/RoomEscape/StoreData.json
  RoomEscape/RoomEscape/ViewControllers/DetailViewController.swift
  RoomEscape/RoomEscape/ViewControllers/HomeViewController.swift
  RoomEscape/RoomEscape/ViewControllers/MainTabBarController.swift
  RoomEscape/RoomEscape/ViewControllers/MakeTeamViewController.swift
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/ViewControllers/TeamCell.swift
  RoomEscape/RoomEscape/ViewControllers/TeamViewController.swift
  RoomEscape/RoomEscape/ViewControllers/ThemeCompareViewController.swift
  RoomEscape/RoomEscape/Views/Base.lproj/Main.storyboard
  RoomEscape/RoomEscape/Views/Detail.storyboard
  RoomEscape/RoomEscape/Views/Home.storyboard
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.swift
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.xib
  RoomEscape/RoomEscape/Views/RoomTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomTableViewCell.xib
  RoomEscape/RoomEscape/Views/Team.storyboard
  RoomEscape/RoomEscape/Views/ThemeCompare.storyboard
Labels: enhancement, ✅ Done

#46 [Feat] ThemeCompare 파트 작업
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Extensions/Constants.swift
  RoomEscape/RoomEscape/Extensions/Extension.swift
  RoomEscape/RoomEscape/Extensions/UILabel+Extension.swift
  RoomEscape/RoomEscape/Managers/JSONDataManager.swift
  RoomEscape/RoomEscape/Models/StoreModel.swift
  RoomEscape/RoomEscape/PohangData.json
  RoomEscape/RoomEscape/ViewControllers/DetailViewController.swift
  RoomEscape/RoomEscape/ViewControllers/HomeViewController.swift
  RoomEscape/RoomEscape/ViewControllers/MakeTeamViewController.swift
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/ViewControllers/TeamCell.swift
  RoomEscape/RoomEscape/ViewControllers/TeamViewController.swift
  RoomEscape/RoomEscape/ViewControllers/ThemeCompareViewController.swift
  RoomEscape/RoomEscape/Views/Base.lproj/Main.storyboard
  RoomEscape/RoomEscape/Views/Detail.storyboard
  RoomEscape/RoomEscape/Views/Home.storyboard
  RoomEscape/RoomEscape/Views/HomeCollectionViewCell.swift
  RoomEscape/RoomEscape/Views/HomeTableViewCell.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.xib
  RoomEscape/RoomEscape/Views/RoomTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomTableViewCell.xib
  RoomEscape/RoomEscape/Views/Team.storyboard
  RoomEscape/RoomEscape/Views/ThemeCompare.storyboard
Labels: enhancement

#77 [Refactor] #65 테마 비교뷰 리팩토링 작업
  RoomEscape/RoomEscape/Extensions/UILabel+Extension.swift
  RoomEscape/RoomEscape/ViewControllers/ThemeCompareViewController.swift
  RoomEscape/RoomEscape/Views/ThemeCompare.storyboard
Labels: Refactoring

#78 [Feat] HomeView, SearchDetailView
  RoomEscape/GBZGAppClip/Assets.xcassets/AccentColor.colorset/Contents.json
  RoomEscape/GBZGAppClip/Assets.xcassets/AppIcon.appiconset/Contents.json
  RoomEscape/GBZGAppClip/Assets.xcassets/Contents.json
  RoomEscape/GBZGAppClip/ContentView.swift
  RoomEscape/GBZGAppClip/GBZGAppClip.entitlements
  RoomEscape/GBZGAppClip/GBZGAppClipApp.swift
  RoomEscape/GBZGAppClip/Info.plist
  RoomEscape/GBZGAppClip/Preview Content/Preview Assets.xcassets/Contents.json
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Assets.xcassets/3dClock.imageset/3d-clock.png
  RoomEscape/RoomEscape/Assets.xcassets/3dClock.imageset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/3dGift.imageset/3dGift.png
  RoomEscape/RoomEscape/Assets.xcassets/3dGift.imageset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/3dKey.imageset/3d-key.png
  RoomEscape/RoomEscape/Assets.xcassets/3dKey.imageset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/3dParty.imageset/3dParty.png
  RoomEscape/RoomEscape/Assets.xcassets/3dParty.imageset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/3dTrophy.imageset/3d-trophy.png
  RoomEscape/RoomEscape/Assets.xcassets/3dTrophy.imageset/Contents.json
  RoomEscape/RoomEscape/Extensions/Constants.swift
  RoomEscape/RoomEscape/Info.plist
  RoomEscape/RoomEscape/Models/StoreModel.swift
  RoomEscape/RoomEscape/PohangData.json
  RoomEscape/RoomEscape/ViewControllers/HomeViewController.swift
  RoomEscape/RoomEscape/ViewControllers/SearchDetailViewController.swift
  RoomEscape/RoomEscape/Views/Base.lproj/Main.storyboard
  RoomEscape/RoomEscape/Views/Home.storyboard
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.swift
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.xib
  RoomEscape/RoomEscape/Views/SearchDetail.storyboard
  apple-app-site-association.rtf
Labels: enhancement

#80 [Feat] 서치 뷰 작업 사항 + 탭바 관련 요청 사항 추가
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/ViewControllers/SearchResultViewController.swift
  RoomEscape/RoomEscape/ViewControllers/SearchViewController.swift
  RoomEscape/RoomEscape/Views/Base.lproj/Main.storyboard
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/Search.storyboard
  RoomEscape/RoomEscape/Views/SearchResult.storyboard
Labels: enhancement

#81 2차 스프린트 수정 및 추가사항 구현
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Assets.xcassets/3dPick.imageset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/3dPick.imageset/Frame 31.png
  RoomEscape/RoomEscape/Assets.xcassets/3dPick.imageset/Frame 31@2x.png
  RoomEscape/RoomEscape/Assets.xcassets/3dPick.imageset/Frame 31@3x.png
  RoomEscape/RoomEscape/Assets.xcassets/3dRocket.imageset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/3dRocket.imageset/Frame 32.png
  RoomEscape/RoomEscape/Assets.xcassets/3dRocket.imageset/Frame 32@2x.png
  RoomEscape/RoomEscape/Assets.xcassets/3dRocket.imageset/Frame 32@3x.png
  RoomEscape/RoomEscape/Extensions/Constants.swift
  RoomEscape/RoomEscape/Extensions/Extension.swift
  RoomEscape/RoomEscape/Models/StoreModel.swift
  RoomEscape/RoomEscape/ViewControllers/MakeTeamViewController.swift
  RoomEscape/RoomEscape/ViewControllers/PickViewController.swift
  RoomEscape/RoomEscape/ViewControllers/TeamCell.swift
  RoomEscape/RoomEscape/ViewControllers/TeamViewController.swift
  RoomEscape/RoomEscape/Views/Pick.storyboard
  RoomEscape/RoomEscape/Views/RoomSelectionTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomSelectionTableViewCell.xib
  RoomEscape/RoomEscape/Views/RoomTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomTableViewCell.xib
  RoomEscape/RoomEscape/Views/Team.storyboard
Labels: enhancement

#85 [Feat] Scroll 추가, Collection View 추가
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Assets.xcassets/Speaker.imageset/Contents.json
  RoomEscape/RoomEscape/Assets.xcassets/Speaker.imageset/Speaker.png
  RoomEscape/RoomEscape/Assets.xcassets/Speaker.imageset/Speaker@2x.png
  RoomEscape/RoomEscape/Assets.xcassets/Speaker.imageset/Speaker@3x.png
  RoomEscape/RoomEscape/Info.plist
  RoomEscape/RoomEscape/ViewControllers/SearchDetailResultViewController.swift
  RoomEscape/RoomEscape/Views/SearchDetailResult.storyboard
  Speaker.png
  Speaker@2x.png
  Speaker@3x.png
Labels: enhancement

#86 [Feat] Detail, PickSheet 워딩 수정
  RoomEscape/RoomEscape/Views/Detail.storyboard
  RoomEscape/RoomEscape/Views/PickSheet.storyboard
Labels: enhancement, ✅ Done

#87 [Feat] 방탈출 이름으로 서치 기능 추가
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/ViewControllers/SearchResultViewController.swift
  RoomEscape/RoomEscape/ViewControllers/SearchViewController.swift
  RoomEscape/RoomEscape/Views/Search.storyboard
  RoomEscape/RoomEscape/Views/SearchResult.storyboard
Labels: enhancement

#88 [FEAT] 방탈출 테마 리스트 공유 기능 추가
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/Extensions/Extension.swift
  RoomEscape/RoomEscape/Info.plist
  RoomEscape/RoomEscape/ViewControllers/TeamViewController.swift
  RoomEscape/RoomEscape/Views/ShareScreenshot/DescriptionContainer.swift
  RoomEscape/RoomEscape/Views/ShareScreenshot/ShareScreenShotView.swift
  RoomEscape/RoomEscape/Views/ShareScreenshot/ThemePoster.swift
Labels: enhancement

#95 [Fix] 테마 비교뷰 변경 요청사항 반영
  RoomEscape/RoomEscape/Extensions/UILabel+Extension.swift
  RoomEscape/RoomEscape/ViewControllers/ThemeCompareViewController.swift
  RoomEscape/RoomEscape/Views/ThemeCompare.storyboard
Labels: Refactoring

#94 [Feat] JSON 아이디를 이용한 Navigation Control
  RoomEscape/RoomEscape/ViewControllers/AllThemeViewController.swift
  RoomEscape/RoomEscape/ViewControllers/HomeViewController.swift
  RoomEscape/RoomEscape/Views/AllTheme.storyboard
  RoomEscape/RoomEscape/Views/RoomCollectionViewCell.swift
Labels: enhancement

#97 [fix] 테마 비교뷰 매장명, 테마명 간격 조정
  RoomEscape/RoomEscape/Views/ThemeCompare.storyboard
Labels: Refactoring

#99 [Feat] TeamView 삭제하기 기능 추가
  RoomEscape/RoomEscape/Extensions/Extension.swift
  RoomEscape/RoomEscape/Models/TeamModel.swift
  RoomEscape/RoomEscape/ViewControllers/TeamViewController.swift
  RoomEscape/RoomEscape/Views/RoomSelectionTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomSelectionTableViewCell.xib
  RoomEscape/RoomEscape/Views/RoomTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomTableViewCell.xib
  RoomEscape/RoomEscape/Views/ShareScreenshot/DescriptionContainer.swift
  RoomEscape/RoomEscape/Views/ShareScreenshot/ShareScreenShotView.swift
Labels: enhancement

#101 [Fix] 서치 결과뷰에서 push navigation 되도록 수정, 탭바, 네비게이션바 투명도 수정
  RoomEscape/RoomEscape/SceneDelegate.swift
  RoomEscape/RoomEscape/ViewControllers/SearchResultViewController.swift
  RoomEscape/RoomEscape/ViewControllers/TeamViewController.swift
  RoomEscape/RoomEscape/Views/RoomSelectionTableViewCell.swift
  RoomEscape/RoomEscape/Views/RoomSelectionTableViewCell.xib
  RoomEscape/RoomEscape/Views/SearchResult.storyboard
Labels: bug

#102 [Style] json "storeName" 수정
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/StoreData.json
Labels: bug

#103 [Feat] Search Logic, Location Detection
  RoomEscape/RoomEscape/Info.plist
  RoomEscape/RoomEscape/ViewControllers/HomeViewController.swift
  RoomEscape/RoomEscape/ViewControllers/SearchDetailViewController.swift
Labels: enhancement

#106 [Style] json "genre" 수정 & button 워딩 수정
  RoomEscape/RoomEscape/StoreData.json
  RoomEscape/RoomEscape/ViewControllers/SearchViewController.swift
  RoomEscape/RoomEscape/Views/Team.storyboard
Labels: Refactoring

#110 [Fix] json 테마설명 수정
  RoomEscape/RoomEscape.xcodeproj/project.pbxproj
  RoomEscape/RoomEscape/StoreData.json
Labels: bug
